# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Grillo Docs
email: info@grillo.io
description: >- # this means to ignore newlines until "baseurl:"
  Information about Grillo Products
#baseurl: "/" # the subpath of your site, e.g. /blog
#url: "https://grillo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
url: ""
baseUrl: ""
#twitter_username: grilloalerta
#github_username: grilloalerta

#footer_content: "Copyright &copy; 2021 Grillo Holdings Inc. Distributed by an <a href=\"https://github.com/grillo/grillo-docs/blob/main/LICENSE">Apache 2 license.</a>"

# Build settings
remote_theme: just-the-docs/just-the-docs
#remote_theme: pmarsceill/just-the-docs@v0.3.2

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

logo: "/assets/images/grillo white svg logo.svg"
search_enabled: true

aux_links:
  "Grillo Website": "//grillo.io"

color_scheme: dark
